version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cslite-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cslite
      MYSQL_USER: cslite
      MYSQL_PASSWORD: cslitepassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cslite-network

  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    container_name: cslite-server
    environment:
      CSLITE_PORT: 8080
      CSLITE_MODE: production
      CSLITE_DB_DSN: cslite:cslitepassword@tcp(mysql:3306)/cslite?charset=utf8mb4&parseTime=True&loc=Local
      CSLITE_SECRET_KEY: your-secret-key-here-change-in-production
      CSLITE_JWT_SECRET: your-jwt-secret-here-change-in-production
      CSLITE_API_RATE_LIMIT: 60
      CSLITE_ALLOW_REGISTER: "true"
      CSLITE_FILE_DIR: /var/cslite/files
      CSLITE_CRON_ENABLED: "true"
    ports:
      - "8080:8080"
    volumes:
      - server_files:/var/cslite/files
    depends_on:
      - mysql
    networks:
      - cslite-network
    restart: unless-stopped

volumes:
  mysql_data:
  server_files:

networks:
  cslite-network:
    driver: bridge